services:
  dms-admin:
    build: .
    container_name: dms-admin-container  # Name your container for easier reference
    ports:
      - "443:8080"
    networks:
      - app-network  # Optional: specify network if needed
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../../docker-data/dms/config/postfix-accounts.cf:/app/postfix-accounts.cf:ro
      - ../../docker-data/dms/config/postfix-virtual.cf:/app/postfix-virtual.cf:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  app-network:  # Optional: define a custom network if you have multiple services
    driver: bridge
    
