services:
  dms-admin:
    build: .
    container_name: dms-admin-container  # Name your container for easier reference
    ports:
      - "443:8080"
    networks:
      - app-network  # Optional: specify network if needed
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ../../docker-data/dms/config/postfix-accounts.cf
        target: /app/postfix-accounts.cf
      - type: bind
        source: ../../docker-data/dms/config/postfix-virtual.cf
        target: /app/postfix-virtual.cf

networks:
  app-network:  # Optional: define a custom network if you have multiple services
    driver: bridge
