services:
  dms-admin:
    build: .
    container_name: dms-admin-container  # Name your container for easier reference
    ports:
      - "80:8080"  # Map port 80 on host to port 8080 in the container
      - "443:8080"
    networks:
      - app-network  # Optional: specify network if needed
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../../docker-data/dms/config/postfix-accounts.cf:/app:ro

networks:
  app-network:  # Optional: define a custom network if you have multiple services
    driver: bridge
